/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
      {
        "_edit_event_id": "0.6668756126702717",
        "selector": ".U2",
        "center": {
          "x": -5.004250626566417,
          "y": 0.13319298245614064
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.867524742177592",
        "selector": ".R1",
        "center": {
          "x": 2.8351077694235585,
          "y": 0
        },
        "relative_to": "group_center"
      }
    ],
  manual_trace_hints: [],
  edit_events: [],
}
