/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
    {
      _edit_event_id: "0.6668756126702717",
      selector: ".U2",
      center: {
        x: -5.830346475507767,
        y: -1.3620071684587813,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.867524742177592",
      selector: ".R1",
      center: {
        x: 3.679808841099163,
        y: 3.6320191158900847,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.4555106760070762",
      selector: ".C1",
      center: {
        x: 0,
        y: 2.6666666666666665,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.6123290063979561",
      selector: ".R2",
      center: {
        x: 13.457749922536511,
        y: 5.576084911465589,
      },
      relative_to: "group_center",
    },
  ],
  manual_trace_hints: [
    {
      "pcb_port_selector": ".SW4 > .pin2",
      "offsets": [
        {
          "x": -8.492199000694345,
          "y": -1.998912735924403,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".SW7 > .pin1",
      "offsets": [
        {
          "x": -23.955683342322523,
          "y": 10.88389101192926,
          "via": false
        },
        {
          "x": -16.747386499009068,
          "y": 10.88389101192926,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D1 > .pin2",
      "offsets": [
        {
          "x": -6.6120446397225265,
          "y": -23.571919277339052,
          "via": true
        },
        {
          "x": 32.69781227739724,
          "y": 4.7868824921773,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".SW2 > .pin1",
      "offsets": [
        {
          "x": -4.281249780862737,
          "y": -14.233181814231745,
          "via": true
        },
        {
          "x": 34.20591131679997,
          "y": -5.359753005603952,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".SW8 > .pin1",
      "offsets": [
        {
          "x": -3.288900052520706,
          "y": 15.247231045118642,
          "via": true
        },
        {
          "x": 33.00665141878271,
          "y": -4.88174593519296,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".SW6 > .pin1",
      "offsets": [
        {
          "x": 13.702636532712475,
          "y": -2.1984238421998494,
          "via": true
        },
        {
          "x": 37.17086973641227,
          "y": -10.456476442519742,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".D2 > .pin2",
      "offsets": [
        {
          "x": 12.561114295051617,
          "y": -23.864496542593944,
          "via": true
        },
        {
          "x": 31.243169965739476,
          "y": 6.222709219188005,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".SW1 > .pin2",
      "offsets": [
        {
          "x": -12.08751345122883,
          "y": -21.987424704921573,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".SW4 > .pin1",
      "offsets": [
        {
          "x": -26.011965739587815,
          "y": -1.3280621772648846,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D4 > .pin2",
      "offsets": [
        {
          "x": -11.013535470091448,
          "y": -9.022834789254386,
          "via": true
        },
        {
          "x": 28.754756592538314,
          "y": 12.264328845243295,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".D3 > .pin2",
      "offsets": [
        {
          "x": 30.35063107068494,
          "y": -24.609946154312162,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D9 > .pin2",
      "offsets": [
        {
          "x": 27.764228768984935,
          "y": 11.911837660122025,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".D8 > .pin2",
      "offsets": [
        {
          "x": 23.674326938532413,
          "y": 12.282089990345455,
          "via": true
        }
      ]
    }
  ],
  edit_events: [],
}
