/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
    {
      _edit_event_id: "0.6668756126702717",
      selector: ".U2",
      center: {
        x: -5.830346475507767,
        y: -1.3620071684587813,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.867524742177592",
      selector: ".R1",
      center: {
        x: 3.679808841099163,
        y: 3.6320191158900847,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.4555106760070762",
      selector: ".C1",
      center: {
        x: 0,
        y: 2.6666666666666665,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.6123290063979561",
      selector: ".R2",
      center: {
        x: 13.457749922536511,
        y: 5.576084911465589,
      },
      relative_to: "group_center",
    },
  ],
  manual_trace_hints: [
    {
      "pcb_port_selector": ".SW4 > .pin2",
      "offsets": [
        {
          "x": -8.492199000694345,
          "y": -1.998912735924403,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D4 > .pin2",
      "offsets": [
        {
          "x": -13.122988422132295,
          "y": -8.524891307031254,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D1 > .pin2",
      "offsets": [
        {
          "x": -8.302539134254346,
          "y": -25.869889610856028,
          "via": true
        },
        {
          "x": 32.60178017340978,
          "y": -2.310485746577827,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".SW7 > .pin1",
      "offsets": [
        {
          "x": -23.955683342322523,
          "y": 10.88389101192926,
          "via": false
        },
        {
          "x": -16.747386499009068,
          "y": 10.88389101192926,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".SW4 > .pin1",
      "offsets": [
        {
          "x": -23.904010775309708,
          "y": -3.8845684719809483,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".SW1 > .pin2",
      "offsets": [
        {
          "x": -9.94176262647342,
          "y": -22.9635299104251,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D2 > .pin2",
      "offsets": [
        {
          "x": 13.891002671418706,
          "y": -22.21580740004698,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D3 > .pin2",
      "offsets": [
        {
          "x": 30.876601037632064,
          "y": -25.674952976702208,
          "via": true
        },
        {
          "x": 44.2153867766214,
          "y": 0.20923347590906705,
          "via": true
        }
      ]
    }
  ],
  edit_events: [],
}
