/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
    {
      _edit_event_id: "0.6668756126702717",
      selector: ".U2",
      center: {
        x: -5.830346475507767,
        y: -1.3620071684587813,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.867524742177592",
      selector: ".R1",
      center: {
        x: 3.679808841099163,
        y: 3.6320191158900847,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.4555106760070762",
      selector: ".C1",
      center: {
        x: 0,
        y: 2.6666666666666665,
      },
      relative_to: "group_center",
    },
    {
      _edit_event_id: "0.6123290063979561",
      selector: ".R2",
      center: {
        x: 13.457749922536511,
        y: 5.576084911465589,
      },
      relative_to: "group_center",
    },
  ],
  manual_trace_hints: [
    {
      "pcb_port_selector": ".D9 > .pin2",
      "offsets": [
        {
          "x": 38.92169691522466,
          "y": -2.3377796771400057,
          "via": false
        },
        {
          "x": 37.986379705415004,
          "y": -2.4045880492692646,
          "via": true
        },
        {
          "x": 35.04681133172754,
          "y": -2.5048006074631566,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".D8 > .pin2",
      "offsets": [
        {
          "x": 39.368100153443855,
          "y": 11.075329302388642,
          "via": false
        },
        {
          "x": 39.0431504551313,
          "y": -2.4100831775825498,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".D6 > .pin2",
      "offsets": [
        {
          "x": 27.898990889830188,
          "y": -7.126105014672912,
          "via": true
        }
      ]
    },
    {
      "pcb_port_selector": ".D7 > .pin2",
      "offsets": [
        {
          "x": -8.911022990918022,
          "y": 12.104068965358355,
          "via": true
        },
        {
          "x": 31.337860341638805,
          "y": 8.65338014408593,
          "via": true
        },
        {
          "x": 40.284252655475,
          "y": 7.931249822789734,
          "via": false
        },
        {
          "x": 39.96330584601003,
          "y": -2.4995214848219867,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".SW6 > .pin1",
      "offsets": [
        {
          "x": 14.242563958561936,
          "y": -0.4071654915144425,
          "via": false
        }
      ]
    }
  ],
  edit_events: [],
}
